### ISSUE TITLE
Sorry for all the problems but now after i run the factor bases and roots, and go to find relations the program crashes

### ISSUE THREAD

**Issue by stewcop** [AdamRakaska/GNFS#10]
After finding factor bases, when I click the "find relations" button the program crashes, I dont know if this is just me but here is my output log:
[Output.log.txt](https://github.com/AdamWhiteHat/GNFS/files/4526268/Output.log.txt)

**Comment by AdamWhiteHat** [comment]
It's no bother. Thank you for including the Output.log.txt.

I wanted to let you know I am looking into the issue, and will be in contact shortly about what I find.

If, per chance, I am not in contact shortly, feel free to give me a kick in the shins by replying to this thread.

**Comment by AdamWhiteHat** [comment]
My apologies once again. The issue was not with you, but with me.

Last time, I don't believe I actually tested the fix that I checked in, because I was so confident that it would fix the issue as presented. And while it did, had I actually tested it, I would have discovered another underlying bug, that you instead found. 

Regardless, I have tested this latest fix and it indeed should work for you, so please download the latest and try again.

My apologies for any time of yours that I may have wasted.
