### ISSUE TITLE
Replace for loop in ModularMultiplicativeInverse

### ISSUE THREAD

**Issue by an31146** [AdamRakaska/GNFS#12]
**Proposal/Summary**
Use the extended euclidean gcd algorithm instead of a for loop.

**Rationale**
The for loop is inefficient when compared to using extended euclidean gcd algorithm to calculate multiplicative inverse.

**Implementation**
Details of the extended euclidean gcd are widely available and its use to calculate modular inverse is commonplace in arbitrary precision or big integer libraries.

**Details/Concerns/Other things to consider**
None.

**Comment by AdamWhiteHat** [comment]
Yeah, good call. What a naive implementation. I had a much better implementation kicking around in one of my general maths library that I use all the time, so this was an easy win.
See PR #13. If you're satisfied with this, feel free to close the issue/request. Otherwise I will circle back around in a day or so to close it. I'm just leaving it open in case you had any other commentary or questions regarding this method or approach (I find it rude when people just close the issue after making an update, assuming they understood the issue and satisfactorily fixed the problem, although in this case, it seems clear enough).
If you would like to have a dialog about a different topic, please open a new issue.

Thanks.

**Comment by AdamWhiteHat** [comment]
Kay, I'm closing this.
